# Generated by Django 5.2 on 2025-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('Loan_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Loan_Type', models.CharField(max_length=30)),
                ('Loan_Amt', models.IntegerField()),
                ('cust_accno', models.IntegerField()),
                ('cust_name', models.CharField(max_length=30)),
            ],
        ),
    ]
